name: Bug Report
description: Report a bug encountered when working with EHRbase
labels: ["type:bug"]
body:
  - type: textarea
    attributes:
      label: Environment information
      description: Please provide information about the version of EHRbase for OpenShift 
      placeholder: |
        - Version of HIP EHRbase for OpenShift:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe the steps that you have taken until the unexpected behavior occurred. Please try to add as many details as possible, and include data and templates as attachments.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe the expected output / behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual result
      description: Describe the wrong output / behavior.
    validations:
      required: true
