name: Task Request
description: A general task, e.g. research or other common work to be done
labels: ["type:task"]
body:
  - type: textarea
    attributes:
      label: Background
      description: Describe the goal of this task, and the expectations or impacts on EHRbase after this task has been completed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Task specification
      description: Add specific steps or work descriptions with the expected results.
    validations:
      required: true
